[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "synthetic-medical-notes"
version = "1.0.0"
authors = [
    { name="Zella King", email="zella.king@ucl.ac.uk" }
]
readme = "README.md"
requires-python = ">=3.10"
